version: '3'
services:
  db:
    image: keinos/sqlite3:latest

  app:
    image: node:16

    environment:
      - DEBUG=app:*
      - PORT=80

    tty: true

    ports:
      - '80:80'

    volumes:
      - ./src:/app

    working_dir: /app

    command: >
      bash -c "npm install &&
      npm run start"